[package]
name = "godot_asset_browser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = "0.1.3"

[build-dependencies]
# Add any build dependencies here if neededstyst